# Generated by Django 6.0.7 on 2026-07-19 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='Year',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='username',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AlterField(
            model_name='nurse',
            name='nurse_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('B.Sc CS', 'B.Sc Computer Science'), ('BCA', 'Bachelor of Computer Applications'), ('B.Com', 'Bachelor of Commerce'), ('BBA', 'Bachelor of Business Administration'), ('B.Sc Maths', 'B.Sc Mathematics'), ('B.Sc Physics', 'B.Sc Physics'), ('B.Sc Chemistry', 'B.Sc Chemistry'), ('B.Sc Zoology', 'B.Sc Zoology'), ('B.Sc Botany', 'B.Sc Botany'), ('BA English', 'BA English'), ('BA Tamil', 'BA Tamil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
