# Generated by Django 6.0.7 on 2026-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_rename_year_student_year_remove_nurse_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=150, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentVisit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('problem', models.TextField()),
                ('medicine', models.CharField(max_length=255)),
                ('staff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('chronic_illness', models.CharField(default='No', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='qualification',
            new_name='quazlification',
        ),
    ]
