# Generated by Django 6.0.7 on 2026-07-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_medicineinventory_studentvisit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='quazlification',
            new_name='qualification',
        ),
    ]
