# Generated by Django 6.0.7 on 2026-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_rename_quazlification_nurse_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('B.Sc CS', 'B.Sc Computer Science'), ('BCA', 'Bachelor of Computer Applications'), ('B.Com', 'Bachelor of Commerce'), ('BBA', 'Bachelor of Business Administration'), ('B.Sc Maths', 'B.Sc Mathematics'), ('B.Sc Physics', 'B.Sc Physics'), ('B.Sc Chemistry', 'B.Sc Chemistry'), ('B.Sc Zoology', 'B.Sc Zoology'), ('B.Sc Botany', 'B.Sc Botany'), ('BA English', 'BA English'), ('BA Tamil', 'BA Tamil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentvisit',
            name='chronic_illness',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentvisit',
            name='problem',
            field=models.CharField(choices=[('Fever', 'Fever'), ('Headache', 'Headache'), ('Cold & Cough', 'Cold & Cough'), ('Stomach Pain', 'Stomach Pain'), ('Body Pain', 'Body Pain')], max_length=100),
        ),
    ]
