# Generated by Django 6.0.7 on 2026-07-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_staff_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvisit',
            name='next_checkup',
            field=models.DateField(blank=True, null=True),
        ),
    ]
