# Generated by Django 6.0.7 on 2026-07-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_studentvisit_next_checkup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvisit',
            name='next_checkup',
        ),
        migrations.AddField(
            model_name='studentvisit',
            name='follow_up_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
