# Generated by Django 6.0.7 on 2026-08-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_remove_studentvisit_next_checkup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='Assistant Professor', max_length=100),
            preserve_default=False,
        ),
    ]
