# Generated by Django 6.0.7 on 2026-10-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvisit',
            name='dosage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
