# Generated by Django 6.0.7 on 2026-10-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_studentvisit_dosage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvisit',
            name='dosage',
        ),
    ]
