# Generated by Django 6.0.7 on 2026-10-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_remove_studentvisit_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvisit',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='Account.student'),
        ),
    ]
